/*
 * Ukrainian translation
 * @author Ivan Chyr <ichyr@softserveinc.com>
 * @version 2014-06-18
 */
(function($) {
elRTE.prototype.i18Messages.ua = {
  '_translator'    : 'Ivan Chyr &lt;ichyr@softserve.inc&gt;',
  '_translation'   : 'Український переклад',
  'Editor' : 'Редактор',
  'Source' : 'Вихідний кож',
  // названия панелей
  'Copy/Pase'      : 'Копіювання/Вставка',
  'Undo/Redo'      : 'Відміна/Повтор дії',
  'Text styles'    : 'Стилі тексту',
  'Colors'         : 'Кольори',
  'Alignment'      : 'Вирівнювання',
  'Indent/Outdent' : 'Відступи',
  'Text format'    : 'Форматування',
  'Lists'          : 'Списки',
  'Misc elements'  : 'Різні елементи',
  'Links'          : 'Посилання',
  'Images'         : 'Зображення',
  'Media'          : 'Media файли',
  'Tables'         : 'Таблиці',
  'File manager (elFinder)' : 'Файловий менеджер (elFinder)',
  // названия кнопок
  'About this software'     : 'Про програму',
  'Save'                    : 'Зберегти',
  'Copy'                    : 'Копіювати',
  'Cut'                     : 'Вирізати',
  'Paste'                   : 'Вставити',
  'Paste only text'         : 'Вставити тільки текст',
  'Paste formatted text'    : 'Вставити відформатований текст',
  'Clean format'            : 'Видалити форматування', 
  'Undo last action'        : 'Відмінити дію',
  'Redo previous action'    : 'Повторити дія',
  'Bold'                    : 'Жирний',
  'Italic'                  : 'Курсив',
  'Underline'               : 'Підкреслений',
  'Strikethrough'           : 'Перекреслений',
  'Superscript'             : 'Верхній індекс',
  'Subscript'               : 'Індекс',
  'Align left'              : 'Вирівнювати по лівій стороні',
  'Ailgn right'             : 'Вирівнювати по правій стороні',
  'Align center'            : 'Вирівнювати по центру',
  'Align full'              : 'Вирівнювати по краях',
  'Font color'              : 'Колір шрифту',
  'Background color'        : 'Колір заливки',
  'Indent'                  : 'Збільшити відступ',
  'Outdent'                 : 'Зменшити відступ',
  'Format'                  : 'Форматування',
  'Font size'               : 'Розмір шрифру',
  'Font'                    : 'Шрифт',
  'Ordered list'            : 'Нумерований список',
  'Unordered list'          : 'Ненумерований список',
  'Horizontal rule'         : 'Горизонтальна лінія',
  'Blockquote'              : 'Цитата',
  'Block element (DIV)'     : 'Блочний элемент (DIV)',
  'Link'                    : 'Посилання',
  'Delete link'             : 'Видалити посилання',
  'Bookmark'                : 'Закладка',
  'Image'                   : 'Зображення',
  'Table'                   : 'Таблиця',
  'Delete table'            : 'Видалити таблицю',
  'Insert row before'       : 'Вставити рядочок перед',
  'Insert row after'        : 'Вставити рядочок після',
  'Delete row'              : 'Видалити рядочок',
  'Insert column before'    : 'Вставити колонку перед',
  'Insert column after'     : 'Вставити колонку після',
  'Delete column'           : 'Видалити колонку',
  'Merge table cells'       : 'Об’єднати комірки таблиці',
  'Split table cell'        : 'Разделить ячейку',
  'Toggle display document structure' : 'Показати структуру документу/невидимі елементи',
  'Table cell properties'   : 'Властивості комірки',
  'Table properties'        : 'Властивості таблиці',
  'Toggle full screen mode' : 'Повноекранний режим',
  'Open file manager'       : 'Відобразити файловий менеджер',
  'Non breakable space'     : 'Неподільний пробіл',
  'Stop element floating'   : 'Відключити обтікання елементів текстом',
  // dialogs
  'Warning' : 'Увага',
  'Properies' : 'Властивості',
  'Popup' : 'Нове вікно',
  'Advanced' : 'Додадково',
  'Events' : 'Події',
  'Width' : 'Ширина',
  'Height' : 'Висота',
  'Left'   : 'Зліва',
  'Center' : 'По центру',
  'Right'  : 'Справа',
  'Border' : 'Межа',
  'Background' : 'Фон',
  'Css class' : 'css клас',
  'Css style' : 'css cтиль',
  'No' : 'Ні',
  'Title' : 'Заголовок',
  'Script direction' : 'Напрямок тексту',
  'Language' : 'Мова',
  'Charset' : 'Кодування',
  'Not set' : 'Не визначено',
  'Left to right' : 'Зліва направо',
  'Right to left' : 'Справа наліво',
  'In this window' : 'У цьому вікні',
  'In new window (_blank)' : 'У новому вікні (_blank)',
  'In new parent window (_parent)' : 'У батьківському вікні (_parent)',
  'In top frame (_top)' : 'У верхньому фреймі (_top)',
  'URL' : '',
  'Open in' : 'Відкрити',
  'Open file manger' : 'Відкрити файловий менеджер',
  // copy
  'This operation is disabled in your browser on security reason. Use shortcut instead.' : 'Ця дія є забороненою у вашому браузері. Будь ласка використовуйте відполвідну комбінацію клавіш.',
  // format 
  'Heading 1' : 'Заголовок 1',
  'Heading 2' : 'Заголовок 2',
  'Heading 3' : 'Заголовок 3',
  'Heading 4' : 'Заголовок 4',
  'Heading 5' : 'Заголовок 5',
  'Heading 6' : 'Заголовок 6',  
  'Paragraph' : 'Параграф',
  'Address' : 'Адреса',
  'Preformatted' : 'Наперед відформатований',
  // font size
  'Small (8pt)'   : 'Дрібний (8pt)',
  'Small (10px)'  : 'Маленький (10px)',
  'Small (12pt)'  : 'Не великий (12pt)',
  'Normal (14pt)' : 'Звичайний (14pt)',
  'Large (18pt)'  : 'Великий (18pt)',
  'Large (24pt)'  : 'Крупний (24pt)',
  'Large (36pt)'  : 'Величезний (36pt)',        
  // bookmark
  'Bookmark name' : 'Ім’я закладки',
  // link
  'Link URL' : 'Адреса гіперпосилання (URL)',
  'Target' : 'Ціль',
  'Select bookmark' : 'Вибрати закладку',
  'Open link in popup window' : 'Відкрити посилання спливаючому вікні',
  'URL' : '',
  'Window name' : 'Назва вікна',
  'Window size' : 'Розмір вікна',
  'Window position' : 'Позиція вікна',
  'Location bar' : 'Панель локації',
  'Menu bar' : 'Панель меню',
  'Toolbar' : 'Панель інструментів',
  'Scrollbars' : 'Полоси прокрутки',
  'Status bar' : 'Рядок стану',
  'Resizable' : 'Зміна розміру',
  'Depedent' : 'Залужний (Netscape)',
  'Add return false' : 'Додати (return false)',
  'Target MIME type' : 'MIME type цілі',
  'Relationship page to target (rel)' : 'Відношення сторінки до цілі (rel)',
  'Relationship target to page (rev)' : 'Відношення цілі до сторінки (rev)',
  'Tab index' : 'Номер вкладки',
  'Access key' : 'Клавіша доступу',
  // image
  'Size' : 'Розмір',
  'Preview' : 'Попередній перегляд',
  'Margins' : 'Відступи',
  'Alt text' : 'Опис (Alt)',
  'Image URL' : 'Шлях до малюнку',
  // table
  'Spacing'       : 'Інтервал (spacing)',
  'Padding'       : 'Відступ (padding)',
  'Rows'          : 'Рядки',
  'Columns'       : 'Колонки',
  'Groups'        : 'Групи',
  'Cells'         : 'Комірки',
  'Caption'       : 'Заголовок таблиці',
  'Inner borders' : 'Внутрішні межі',
  // table cell
  'Table cell type' : 'Тип комірки',
  'Data' : 'Дані',
  'Header' : 'Заголовок',
  'Justify' : 'По краях',
  'Paddings' : 'Відступи',
  'Apply to' : 'Застосувати до',
  'Current cell' : 'Вибрана комірка',
  'All cells in row' : 'Всі комірки в рядку',
  'All cells in column' : 'Всі комірки в колонці',
  'All cells in table' : 'Всі комірки таблиці',
  // about
  'About elRTE' : 'Про редактор elRTE',
  'Version' : 'Версія',
  'Licence' : 'Ліцензія',
  'elRTE is an open-source JavaScript based WYSIWYG HTML-editor.' : 'elRTE - це вільний WYSIWYG редактор для сайтів и систем управління вмістом (CMS), написаний на JavaScript.',
  'Main goal of the editor - simplify work with text and formating (HTML) on sites, blogs, forums and other online services.' : 'Основная ціль редактора - максимально спростити роботу з текстом и розміткой (HTML) на сайтах, блогах, форумах та інших online сервісах.',
  'You can use it in any commercial or non-commercial projects.' : 'Ви можете використовувати його в будь-яких комерційних або некомерційних проектах.',
  'Authors' : 'Автори',
  'Chief developer' : 'Головний розробник',
  'Developer, tech support' : 'Розробник, технічна підтримка',
  'Developer' : 'Розробник',
  'Interface designer' : 'Дизайнер інтерфейсу',
  'Spanish localization' : 'Іспанська локалізація',
  'Czech localization' : 'Чеська локалізація',
  'Japanese localization' : 'Японска локалізація',
  'Latvian localization' : 'Латвійська локалізація',
  'German localization' : 'Німецька локалізація',
  'Ukranian localization' : 'Українська локалізація',
  'Persian (farsi) localization' : 'Персицька (фарсі) локалізація',
  'Arabic localization' : 'Арабска локалізація',
  'RTL support' : 'Підтримка RTL',
  'French localization' : 'Французька локалізація',
  'Dutch localization' : 'Голландська локалізація',
  'Hungarian localization' : 'Угорська локалізація',
  'Polish localization' : 'Польска локалізація',
  'Italian localization' : 'Італійська локалізація',
  'Traditional Chinese localization' : 'Китайска (традиційна) локалізація',
  'For more information about this software visit the' : 'Докладна інфомрація і форму технічної підтримки',
  'elRTE website' : 'на сайті elRTE' 
}
})(jQuery);
